#!/bin/sh
# chkconfig: 35 99 01
# description: Docker Container Zabbix

MY_NAME=`basename ${0}`
PID_FILE=/var/run/${MY_NAME}.pid

case "$1" in
  start)
    docker run -p 10022:22 -p 10080:80 -p 10051:10051 -p 12812:2812 --volumes-from vol_zabbix \
    -d atsushi/cent6_zabbix > $PID_FILE
  ;;
  stop)
    if [ -f $PID_FILE ]; then
      docker stop `cat $PID_FILE`
      rm $PID_FILE
    fi
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  \*)
    echo "usage: $0 (start|stop|restart|help)"
esac

